"""initial

Revision ID: e94a4f8eeddf
Revises: 
Create Date: 2025-04-21 14:05:34.368928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e94a4f8eeddf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        ###batch_op.add_column(sa.Column('attempts', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('attempts', sa.Integer(), nullable=False, server_default='0'))
         

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('attempts')

    # ### end Alembic commands ###
